export const PERMISSIONS = {
  // Read
  READ_ORG: 'READ_ORG',
  READ_HRMS: 'READ_HRMS',
  READ_CRM: 'READ_CRM',
  READ_TENDER: 'READ_TENDER',
  READ_SECURITY: 'READ_SECURITY',
  
  // Write
  WRITE_ORG: 'WRITE_ORG',
  WRITE_HRMS: 'WRITE_HRMS',
  WRITE_CRM: 'WRITE_CRM',
  WRITE_TENDER: 'WRITE_TENDER',
  WRITE_SECURITY: 'WRITE_SECURITY',
};
