import { apiClient } from './axios';
import type { ApiResponse } from '@/types/api';
import type { ResourceApi } from './organization';
import { API_ENDPOINTS } from './endpoints';

type ApiRecord = { id: string;[key: string]: unknown };

const unwrap = async <T>(request: Promise<{ data: ApiResponse<T> }>) => (await request).data.data;

type CrudEndpoints = { list: string; create: string; update?: (id: string) => string; remove?: (id: string) => string };

const crud = (paths: CrudEndpoints, options: { updateMethod?: 'put' | 'patch'; update?: boolean; remove?: boolean } = {}): ResourceApi<any> => ({
  list: () => unwrap(apiClient.get<ApiResponse<ApiRecord[]>>(paths.list)),
  create: (data) => unwrap(apiClient.post<ApiResponse<ApiRecord>>(paths.create, data)),
  ...(options.update === false ? {} : {
    update: (id: string, data: Record<string, unknown>) => options.updateMethod === 'patch'
      ? unwrap(apiClient.patch<ApiResponse<ApiRecord>>(paths.update!(id), data))
      : unwrap(apiClient.put<ApiResponse<ApiRecord>>(paths.update!(id), data))
  }),
  ...(options.remove === false || !paths.remove ? {} : { remove: async (id: string) => { await apiClient.delete(paths.remove!(id)); } }),
});

export const hrmsApi = {
  employees: crud(API_ENDPOINTS.hrms.employees), attendance: crud(API_ENDPOINTS.hrms.attendance), leave: crud(API_ENDPOINTS.hrms.leave),
  salary: crud(API_ENDPOINTS.hrms.salary), holidays: crud(API_ENDPOINTS.hrms.holidays), shifts: crud(API_ENDPOINTS.hrms.shifts),
  documents: crud(API_ENDPOINTS.hrms.documents),
};

export const crmApi = {
  customers: crud(API_ENDPOINTS.crm.customers),

  contacts: crud(API_ENDPOINTS.crm.contacts),

  communications: crud(
      API_ENDPOINTS.crm.communications,
      { update: false }
  ),

};

export const tenderApi = {
  requests: crud(API_ENDPOINTS.tender.requests), tenders: crud(API_ENDPOINTS.tender.tenders),
  governmentDepartments: crud(API_ENDPOINTS.tender.governmentDepartments), sections: crud(API_ENDPOINTS.tender.sections),
  divisions: crud(API_ENDPOINTS.tender.divisions), subDivisions: crud(API_ENDPOINTS.tender.subDivisions),
  technicalClarifications: {
    ...crud(API_ENDPOINTS.tender.technicalClarifications),
    read: (id: string) => unwrap(apiClient.get<ApiResponse<any>>(`/technical-clarification/read/${id}`)),
    reply: (id: string, data: { reply: string; repliedById?: string; isInternal?: boolean }) => unwrap(apiClient.post<ApiResponse<any>>(`/technical-clarification/reply/${id}`, data)),
    addAttachment: (id: string, data: { fileName: string; fileUrl: string; fileSize?: number; mimeType?: string; uploadedById?: string }) => unwrap(apiClient.post<ApiResponse<any>>(`/technical-clarification/attachment/${id}`, data)),
  },
  boqs: crud(API_ENDPOINTS.tender.boqs),
  referenceCodes: {
    list: () => unwrap(apiClient.get<ApiResponse<ApiRecord[]>>(API_ENDPOINTS.tender.referenceCodes.list)),
    create: async () => { throw new Error('Reference codes are generated by the backend.'); },
  } satisfies ResourceApi<any>,
};

