import { apiClient } from './axios';
import type { ApiResponse } from '@/types/api';
import type { ResourceApi } from './organization';
import { API_ENDPOINTS } from './endpoints';

type ApiRecord = { id: string;[key: string]: unknown };

const unwrap = async <T>(request: Promise<{ data: ApiResponse<T> }>) => (await request).data.data;

type CrudEndpoints = { list: string; create: string; update?: (id: string) => string; remove?: (id: string) => string };

const crud = (paths: CrudEndpoints, options: { updateMethod?: 'put' | 'patch'; update?: boolean; remove?: boolean } = {}): ResourceApi<any> => ({
  list: () => unwrap(apiClient.get<ApiResponse<ApiRecord[]>>(paths.list)),
  create: (data) => unwrap(apiClient.post<ApiResponse<ApiRecord>>(paths.create, data)),
  ...(options.update === false ? {} : {
    update: (id: string, data: Record<string, unknown>) => options.updateMethod === 'patch'
      ? unwrap(apiClient.patch<ApiResponse<ApiRecord>>(paths.update!(id), data))
      : unwrap(apiClient.put<ApiResponse<ApiRecord>>(paths.update!(id), data))
  }),
  ...(options.remove === false || !paths.remove ? {} : { remove: async (id: string) => { await apiClient.delete(paths.remove!(id)); } }),
});

export const hrmsApi = {
  employees: crud(API_ENDPOINTS.hrms.employees), attendance: crud(API_ENDPOINTS.hrms.attendance), leave: crud(API_ENDPOINTS.hrms.leave),
  salary: crud(API_ENDPOINTS.hrms.salary), holidays: crud(API_ENDPOINTS.hrms.holidays), shifts: crud(API_ENDPOINTS.hrms.shifts),
  documents: crud(API_ENDPOINTS.hrms.documents),
};

export const crmApi = {
  customers: crud(API_ENDPOINTS.crm.customers),
  contacts: crud(API_ENDPOINTS.crm.contacts),
  communications: crud(
    API_ENDPOINTS.crm.communications,
    { update: false }
  ),
  leads: crud(API_ENDPOINTS.crm.leads),
};

export const tenderApi = {
  requests: crud(API_ENDPOINTS.tender.requests), tenders: crud(API_ENDPOINTS.tender.tenders),
  governmentDepartments: crud(API_ENDPOINTS.tender.governmentDepartments), sections: crud(API_ENDPOINTS.tender.sections),
  divisions: crud(API_ENDPOINTS.tender.divisions), subDivisions: crud(API_ENDPOINTS.tender.subDivisions),
  technicalClarifications: {
    ...crud(API_ENDPOINTS.tender.technicalClarifications),
    read: (id: string) => unwrap(apiClient.get<ApiResponse<any>>(`/technical-clarification/read/${id}`)),
    reply: (id: string, data: { reply: string; repliedById?: string; isInternal?: boolean }) => unwrap(apiClient.post<ApiResponse<any>>(`/technical-clarification/reply/${id}`, data)),
    addAttachment: (id: string, data: { fileName: string; fileUrl: string; fileSize?: number; mimeType?: string; uploadedById?: string }) => unwrap(apiClient.post<ApiResponse<any>>(`/technical-clarification/attachment/${id}`, data)),
  },
  boqs: crud(API_ENDPOINTS.tender.boqs),
  referenceCodes: {
    list: () => unwrap(apiClient.get<ApiResponse<ApiRecord[]>>(API_ENDPOINTS.tender.referenceCodes.list)),
    create: async () => { throw new Error('Reference codes are generated by the backend.'); },
  } satisfies ResourceApi<any>,
};

export const quotationApi = {
  quotations: {
    ...crud(API_ENDPOINTS.quotation.quotations),
    read: (id: string) => unwrap(apiClient.get<ApiResponse<any>>(`/quotation/read/${id}`)),
    submit: (id: string) => unwrap(apiClient.post<ApiResponse<any>>(API_ENDPOINTS.quotation.quotations.submit(id), {})),
    send: (id: string) => unwrap(apiClient.post<ApiResponse<any>>(API_ENDPOINTS.quotation.quotations.send(id), {})),
    respond: (id: string, data: { response: string; remarks?: string }) => unwrap(apiClient.post<ApiResponse<any>>(API_ENDPOINTS.quotation.quotations.respond(id), data)),
    revise: (id: string, data: any) => unwrap(apiClient.post<ApiResponse<any>>(API_ENDPOINTS.quotation.quotations.revise(id), data)),
  },
  items: crud(API_ENDPOINTS.quotation.items),
  approvals: crud(API_ENDPOINTS.quotation.approvals),
  activities: crud(API_ENDPOINTS.quotation.activities, { update: false }),
};

export const salesOrderApi = {
  salesOrders: crud(API_ENDPOINTS.salesOrder.salesOrders),
};

export const approvalRuleApi = {
  approvalRules: crud(API_ENDPOINTS.approvalRule.approvalRules),
};

export const securityApi = {
  users: crud(API_ENDPOINTS.security.users),
  roles: crud(API_ENDPOINTS.security.roles),
  permissions: {
    list: () => unwrap(apiClient.get<ApiResponse<ApiRecord[]>>(API_ENDPOINTS.security.permissions.list)),
    create: async () => { throw new Error('Permissions are read-only.'); },
  } satisfies ResourceApi<any>,
  permissionGroups: crud(API_ENDPOINTS.security.permissionGroups),
};

export const engineeringApi = {
  projects: crud((API_ENDPOINTS as any).engineering.projects),
  drawings: crud((API_ENDPOINTS as any).engineering.drawings),
  boms: crud((API_ENDPOINTS as any).engineering.boms),
};

export const workflowApi = {
  approvalRequests: crud((API_ENDPOINTS as any).workflow.approvalRequests),
};

export const materialApi = {
  materials: crud((API_ENDPOINTS as any).material.materials),
  categories: crud((API_ENDPOINTS as any).material.categories),
  brands: crud((API_ENDPOINTS as any).material.brands),
  specifications: crud((API_ENDPOINTS as any).material.specifications),
};

export const purchaseApi = {
  requests: crud((API_ENDPOINTS as any).purchase.requests),
  orders: crud((API_ENDPOINTS as any).purchase.orders),
  receipts: crud((API_ENDPOINTS as any).purchase.receipts),
};

export const inventoryApi = {
  warehouses: crud((API_ENDPOINTS as any).inventory.warehouses),
  bins: crud((API_ENDPOINTS as any).inventory.bins),
  stocks: crud((API_ENDPOINTS as any).inventory.stocks),
  transfers: crud((API_ENDPOINTS as any).inventory.transfers),
};

export const productionApi = {
  plans: crud((API_ENDPOINTS as any).production.plans),
  workOrders: crud((API_ENDPOINTS as any).production.workOrders),
  logs: crud((API_ENDPOINTS as any).production.logs),
};

export const qualityApi = {
  inspections: crud((API_ENDPOINTS as any).quality.inspections),
  reworks: crud((API_ENDPOINTS as any).quality.reworks),
};

export const logisticsApi = {
  dispatches: crud((API_ENDPOINTS as any).logistics.dispatches),
  vehicles: crud((API_ENDPOINTS as any).logistics.vehicles),
};

export const financeApi = {
  invoices: crud((API_ENDPOINTS as any).finance.invoices),
  payments: crud((API_ENDPOINTS as any).finance.payments),
  expenses: crud((API_ENDPOINTS as any).finance.expenses),
};
